### ISSUE TITLE
Copy to clipboard links do not work on Android

### ISSUE THREAD

**Issue by cybertim** [cybertim/blockwallet#1]
When clicking on addresses with the 'copy' icon the information is not send to the clipboard.

When not using qrcodes but the clipboard, show a warning everywhere!

**Comment by ligi** [comment]
Be careful with this: https://github.com/walleth/walleth/issues/14

**Comment by cybertim** [comment]
in blockwallet (almost) everything is public addreses you're copying

And yes this is a valid concern for the one and only think you would like to be able to copy: for the private key I will implement a warning before it is send to the clipboard

**Comment by ligi** [comment]
Please read the linked issue again - this is also a problem with public addresses - not only for the private key.

**Comment by cybertim** [comment]
you are right, I will think of a smart solution to this issue

**Comment by cybertim** [comment]
Ready for RC2
