### ISSUE TITLE
UI enhancement.  Convert to a local currency.

### ISSUE THREAD

**Issue by brianerdelyi** [cybertim/blockwallet#11]
Although useful to convert coins to a designated local currency, it is a bit annoying to see "-- OFF" when this feature is disabled.  It would be better to display nothing.

It may also be preferred to have a separate setting to disable this only for ERC20 tokens as these likely have no convertible value.

**Comment by cybertim** [comment]
Better convertible value for tokens now implemented in 1.1.0 (android: live, ios: now in review)
This wasn't working correct in the previous version.

Hiding of '-- OFF' is still open tho.

**Comment by cybertim** [comment]
from version 1.2.5 this is implemented (off hides everything from UI)
