### ISSUE TITLE
Can't make transactions 

### ISSUE THREAD

**Issue by reaperfromhell** [cybertim/blockwallet#12]
Every time I try to do a transaction on a custom testnet I get an error.

Error varies with recipient.
One recipient always gives me the `Invalid sender` error

Another always returns
`rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S`

Any logs I should provide?

**Comment by cybertim** [comment]
If you configure your own RPC server and have the RPC server run at testnet the signed transactions are not compatible. This line of code: https://github.com/cybertim/blockwallet/blob/master/src/utils.ts#L9 is set to the mainnet which is used during the signing of the transactions.
I'm labelling this a feature request, I can add a input on the RPC settings panel in the App to define this chain-ID.

**Comment by reaperfromhell** [comment]
That would be a nice feature, yes.

Thank you for the quick response.

**Comment by cybertim** [comment]
chainid option now implemented in 1.1.0 (android: live, ios: now in review)
