### ISSUE TITLE
To be able to create multiple Ethereum addresses! (This would be the first iOS Ethereum wallet with this feature!!!)

### ISSUE THREAD

**Issue by Thomas3520** [cybertim/blockwallet#16]
Hey Tim!
I really like your Ether app! Smooth looking and simple! :-)

I have a suggestion:
Please add the simple feature to be able to create multiple Ethereum addresses. Till now, no other iOS Ethereum wallet has this function, and yours could be the first! :-D

**Comment by cybertim** [comment]
enhancement merged with #6
