### ISSUE TITLE
How To Get GAS for Transaction

### ISSUE THREAD

**Issue by pfke88** [cybertim/blockwallet#17]
Hye.. i am new in using block wallet and i am stuck due to i cant transfer my eth. when i check from transaction failed due to lack of gas cost.. how to get and pay for gas cost appreciate to assist me.

**Comment by cybertim** [comment]
This is strange, though you can't set the gas-price (nor limit) manually yet.
But blockwallet does get the current gasPrice by consulting https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gasprice
This should dynamically add the correct price.
But afaik currently a lot of people are 'dumping' on popular exchanges, which would congest the network currently. Maybe try it later or try another wallet like MEW?

Discussion can continue in this thread: #10

**Comment by pfke88** [comment]
dear cybertim,

i really dont have idea how to use ether wallet.. how i can get the gas cost.. is it need to buy before transfer or just deduct from my ether balance.. i have ether coin in blockwallet but it is stuck there

**Comment by cybertim** [comment]
The issue you describe is not related to Blockwallet perse.

What you are probably trying to do is transfer all your Ether. But if you have 1 ETH and transfer 1 ETH there is no room to cover the mining-fee (gas costs * gas used).

A solution could be:
The estimated transaction costs is shown before you send the transaction to the chain.
Make a new transaction, and try deducting this amount from the total and make it less till the transaction can be made.
