### ISSUE TITLE
Not send to address, incorrect

### ISSUE THREAD

**Issue by jonyrh** [cybertim/blockwallet#18]
I try send eth to address 0xa4ae45e5007dbe2968870bb7dcf894c8973820ca scaning QR-code, but error: Incorrect address

![screen](https://user-images.githubusercontent.com/28771126/30236703-c1c218b6-9538-11e7-9db6-41e6353ab36e.png)

![0xa4ae45e5007dbe2968870bb7dcf894c8973820ca](https://user-images.githubusercontent.com/28771126/30236667-fbc42f00-9537-11e7-8b37-2128d8db5afc.png)

**Comment by cybertim** [comment]
It does work for me if I use http://www.qr-code-generator.com with the same address.

The qrcode you linked contains the following string:

ethereum:0xa4ae45e5007dbe2968870bb7dcf894c8973820ca?amount=0.14

Which is not an address on its own, that is why the scanner fails to recognise it as one.

**Comment by cybertim** [comment]
This issue will be fixed in a future release though: #19
