### ISSUE TITLE
Transactions not loading after updating to ver 1.2.2 (iOS)

### ISSUE THREAD

**Issue by HesselWellema** [cybertim/blockwallet#21]
Tried setting Etherscan.io on Yes and No. Same effect.
No transactions, Only showing Loading Transactions page.
Also not possoble ot add Tokens

**Comment by cybertim** [comment]
Could you elaborate on the iOS version and which device?

**Comment by HesselWellema** [comment]
iOS 11.0.2
MN942ZD/A (iPhone 7)
tnx

**Comment by cybertim** [comment]
The emulator (7) and hardware (updated to 11.0.2 today and tested it on iphone 6) both seem to work fine. Maybe an issue with the etherscan.io within the network?

Does the RPC server (seeing the amount) and Cryptocompare (seeing the value of the ether) still work? Tried a different network? Tried to simply 'kill' the app and restart it?

**Comment by HesselWellema** [comment]
Hi

Figured it out.
After update the setting TouchId was set to No (was yes before update) setting it to Yes solved the problem. Guess you are able to fix this permanently

This message was created on a mobile device. Excuse me for its briefness.
Kind regards, Hessel Wellema

Op 7 okt. 2017 om 13:52 heeft Tim <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The emulator (7) and hardware (updated to 11.0.2 today and tested it on iphone 6) both seem to work fine. Maybe an issue with the etherscan.io<http://etherscan.io> within the network?

Does the RPC server (seeing the amount) and Cryptocompare (seeing the value of the ether) still work? Tried a different network? Tried to simply 'kill' the app and restart it?

**Comment by cybertim** [comment]
Ok, this is strange, but I do get some more reports from iOS users now, so i guess it has to do with the update process somehow. Will try to replicate the issue or try to see why the fingerprint function is misbehaving all the sudden.

Found the issue, it is related to devices having a touchId/Fingerprint reader but did not enable the function within blockwallet.
Version 1.2.3 resolves the issue (already up on google play, in review for iOS as we speak).

**Comment by HesselWellema** [comment]
Tnx. Fast response and solution
