### ISSUE TITLE
[Bug] Token symbol length limit

### ISSUE THREAD

**Issue by munrocket** [cybertim/blockwallet#24]
For now 3 letter is maximum length of ticker symbol in iOS app. But for example MCAP with 4 letter.

**Comment by munrocket** [comment]
Because of this I can't send a my ERC20 tokens to another wallet and get error: "incorrect address or checksum". As i understanded from FAQ your app has sending functional.

**Comment by cybertim** [comment]
Thought there was a 3 char limit, but it seems this is not the case. Will lift the restriction on the input field.

**Comment by cybertim** [comment]
from version 1.2.5 this is implemented

**Comment by munrocket** [comment]
Sounds great
