### ISSUE TITLE
[bug] Can't send token 'kick'

### ISSUE THREAD

**Issue by munrocket** [cybertim/blockwallet#25]
Blokeallet says that adress not valid. But it is ok.

**Comment by cybertim** [comment]
without any information on the contract address or the contract source I cannot do anything..

**Comment by munrocket** [comment]
https://ethplorer.io/address/0xc0e4f45b828aa4aa628e897e5da38d9dc72c2257
https://ethplorer.io/address/0x93e682107d1e9defb0b5ee701c71707a4b2e46bc

**Comment by cybertim** [comment]
could you try scanning the QRCode of the contract address instead? I think it is an issue with the 'clipboard' functionality.

![unknown](https://user-images.githubusercontent.com/5379564/32946360-7b538456-cb97-11e7-9ebd-de305b9eedae.png)
Code for KC coin: 0xc0e4F45b828Aa4aA628e897e5DA38d9dC72C2257

**Comment by cybertim** [comment]
They have been added to the popular token list - you can add them easily without entering the contract address within the app now.
