### ISSUE TITLE
Convert seed phrase

### ISSUE THREAD

**Issue by neuhaus** [cybertim/blockwallet#27]
How do I get from a 24 word seed phrase generated by blockwallet to a 12 word seed phrase that works with Metamask?
I know I can get the private key using the [keytools](https://blockwallet.eu/keytools/), but how do I generate a 12 word seed phrase from the private key?

I hope this issue isn't unwanted here since it isn't strictly specific to blockwallet..

**Comment by cybertim** [comment]
I don't think this is possible, metamask uses [bip44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) as a wallet-solution. Which if i'm not mistaking means they derive all 'keys' for different currencies from one special root-key.

Blockwallet only uses a single ethereum private key which is directly translated to a phrase through bip39 so people can easily write it down. There is no 'root key'.

If you would like to use bip44 I think the only route ahead is generate a complete new [12 words bip39 root key](https://particl.github.io/bip39/bip39-standalone.html) and within the wallet derive a new ethereum address and send all your ethereum to that address. After this you can extract a single private-key from the wallet and put that one back into blockwallet.

**Comment by neuhaus** [comment]
I managed to import the private key into Metamask using the "import key" feature (you only see it when managing accounts).
