### ISSUE TITLE
Blockwallet (geth RPC) server is currently not in sync

### ISSUE THREAD

**Issue by ramin2013** [cybertim/blockwallet#29]
I have transferred my Ether coins to my wallet. I can see the transaction in my wallet but it is still showing 0 balance in my wallet and I can't send any coins.

**Comment by cybertim** [comment]
Are they still not showing up? Most of the time it is just some delay between etherscan (= showing the transactions) and the blockwallet rpc (= showing the exact value on top).

**Comment by FabSa012** [comment]
I have similar problem. Ether balance is not correctly shown after transaction went out. (12 hours ago).
Also, I have another pending outgoing transaction since 10 hours. Don't know if this is somehow related. (Etherscan is not listing it)

**Comment by cybertim** [comment]
Looks like the blockwallet RPC server is behind a few (3000) blocks, don't know why this is.
So I restarted the Geth RPC server, hopefully it will sync up to the tops (looks like it - can take an hour I guess for it to be fully synced) :)

**Comment by FabSa012** [comment]
Thanks! I got another transaction in which worked perfectly fine. However ether balance is wrong. The earlier mentioned outgoing transactions are still pending.

**Comment by cybertim** [comment]
The RPC server is now on block 4755159 (of 4759599), so it is not fully synced yet. I think it will take another 2 hours or so.

**Comment by ramin2013** [comment]
Thanks, my ether balance is updated now.

**Comment by cybertim** [comment]
The server is now on block 4758086 (of 4760339) its getting closer... only 2000 to go :-)

**Comment by cripsy** [comment]
Hello Mate, I think I'm experiencing the same issue here. I recieved an incoming transaction this morning that is reflected on etherscan and is sitting in the transaction overview but not in the total ether balance. I've read the above and given it 3 hours but no luck yet. Could you advise a fix please. Cheers.

**Comment by cybertim** [comment]
Checked the server again, it was 'hanging' @ block 4786343 and it should be around block 4789139 - again a 3000 blocks difference. Did another restart, and it looks like it is syncing again. Total ether balance should be correct within one or two hours from now.

**Comment by cripsy** [comment]
Ok thanks - the feed did update. It was a bit of a song and dance getting the stuff out - with delayed pendings etc but managed to get it all out in the end. Cheers.

**Comment by cybertim** [comment]
For now I switched the blockwallet RPC service in the backend to INFURA (mainnet.infura.io). Seems to work great, so this issue shouldn't occur anymore (I hope).
