### ISSUE TITLE
Bad transactions - failed and

### ISSUE THREAD

**Issue by NorCalDude** [cybertim/blockwallet#31]
b6fe359f5d6cd44e003c317f1f70a1b4c6e2a9fa3721b55d81d32dfc7dcd7a4c
This transaction shows as complete in Blockwallet but I don’t see it on the receiving address. I have no issues with using MyEtherWallet nor when using CoinSpace app wallet, both of which I’ve used dozens of times without issues.  I was easily able to send Ether from MyEtherWalet to Blockwallet, so no complaints receiving funds to Blockwallet. So why am I having issues with sending from Blockwallet? On the transaction above there should have been plenty of Gas. How can I avoid these issues using Blockwallet moving forward? And how Can I get the funds to show up for this last transaction back into MyEtherWallet where I sent them in the transaction listed above?

These transaction listed below both failed:
5c6538d515a696d22bd77cb881f08fcdcdfd640480698b3bb02e577a7c645d11

d3519172c5e0fbed818ab6f3e4bcc3630e251b88dd47316270f17799751464b3

**Comment by NorCalDude** [comment]
Although MyEtherWallet does not show the amount yet in the MetaMask interface, I do see that latest transaction listed “success” in Ehterscan at this point. If it doesn’t show up in MetaMask, I’ll take the issue up with them. The other two transactions were addressed to Bittrex, but both came back into Blockwaller after failing. I do appreciate not losing the funds outright, so thanks for that. Any suggestions on how to better use Blockwallet to avoid failures like those sent to Bittrex? I know my very first transaction did not have enough Gas, but the second one should have been fine (maybe rejected from Bittrex because that second attempt was too small an amount is my guess). It was hard to know how  to know if enough Gas was allocated or how to raise the amount to guarantee the transaction would succeed.

**Comment by cybertim** [comment]
The first transaction should have been received (it's what the blockchain tells us) so blockwallet was correct to say it was complete... maybe the receiving party is using a slower wallet?

As far as I can tell by the other two transaction hashes you are sending Ether to a closed source contract. I cannot give you any insight on this issue else then asking the creator of the contract how much Gas is needed at least. Poorly designed contracts tend to use a LOT of gas. You can change the gas usage within blockwallet (Settings-tab and you need the normal Gas Limit parameter).

**Comment by cybertim** [comment]
Closing the issue for now. You can reopen if it is still an issue. On a side note: The new Blockwallet version 2 has a better interface for sending ether and tokens (gas limit and fee's can be micro managed). It also has the 'confirmations' in the transaction history.
