### ISSUE TITLE
Token list

### ISSUE THREAD

**Issue by hooka123** [cybertim/blockwallet#36]
Can trx Tron go onto the popular list. Thanks Craig

**Comment by cybertim** [comment]
TRX has been added to the token list, but their contract looks like it is broken, so be alert on this one.

**Comment by hooka123** [comment]
Thank for the info

**Comment by hooka123** [comment]
Having trouble listing litecoin ( LTC ) could you help , thank you

**Comment by cybertim** [comment]
Unless there is also an ERC20 Token called Litecoin, this is impossible since the original Litecoin is on a completely different blockchain not associated with Ethereum.

**Comment by hooka123** [comment]
That would be the reason. Thanks

**Comment by hooka123** [comment]
Bit of trouble loading savedroid SVD 0xbdEB4b83251Fb146687fa19D1C660F99411eefe3 to the token list could you help please

**Comment by hooka123** [comment]
Sorted my issue sorry to bother you . Thanks

**Comment by hooka123** [comment]
Trying to load       Mfg 0x7D855eeD5B3a604ef14aDe753cbcd133A29D871f   Telling me token already added but can’t seem to find. Thanks

**Comment by hooka123** [comment]
Having trouble adding faceter 0x1CCAA0F2a7210d76E1fDec740d5F323E2E1b1672 to list could you try please
