### ISSUE TITLE
Default the App to portrait mode

### ISSUE THREAD

**Issue by hooka123** [cybertim/blockwallet#37]
Trying to send coin address inputted,  numerical key pad appears? Does nothing can’t seem to senb

**Comment by cybertim** [comment]
When the numerical key pad shows up and you type some number, does it show on the screen? If so, you will see the big Blue Button on the right as well. Click on that to continue and sign the Transaction.
If you do not see this button, could you elaborate on the device you are using? (Android? screen size?)

**Comment by hooka123** [comment]
Buttons pressed doesn’t show on screen ,using iPad Air 2, 10 inch no big
blue button.

**Comment by cybertim** [comment]
Here is an example of what the Send screen should look like. The blue button on the right. Is the numerical pad maybe overlapping this part of the screen?
![simulator screen shot - iphone x - 2018-01-11 at 15 59 46](https://user-images.githubusercontent.com/5379564/34831876-8c9f255e-f6e8-11e7-80df-50986422f660.png)

**Comment by hooka123** [comment]
The numerical pad covers everything cannot move

**Comment by cybertim** [comment]
In the next update the App will default to portrait mode, it looks like everything is covered when using landscape mode on the send-screen.
For now you can just use the iPad in portrait mode, this will solve the issue.

**Comment by hooka123** [comment]
Locked no rotation in portrait no change still covering screen.

**Comment by cybertim** [comment]
That is strange, I will try this in the emulator this week with the iPad Air 2 10-inch to see what is happening.

**Comment by cybertim** [comment]
Is fixed now in version 2.0.4 and onward. (released on Android, submitted today for iOS)

**Comment by hooka123** [comment]
Thanks, could you add travelflex trf to the list,

**Comment by cybertim** [comment]
You can make requests for the popular lists (by answering the questions) here: #38
