### ISSUE TITLE
Blockwallet is stuck showing "Refreshing Transactions"

### ISSUE THREAD

**Issue by ramin2013** [cybertim/blockwallet#39]
Blockwallet unable to Sync. Showing "Refreshing Transactions" and can't fetch the Ether balance.

**Comment by cybertim** [comment]
This is correct - currently the server is unresponsive - trying to see what is going on but it looks like an issue at the hosting company or a DDOS attack @ the company or server.

**Comment by cybertim** [comment]
Should be working again.
