### ISSUE TITLE
Token value / price

### ISSUE THREAD

**Issue by svenjatzu** [cybertim/blockwallet#42]
Hey i try to find out which exchange your app uses to sync the prices. 
I can’t find it out.
Can you please tell me the exchange?

**Comment by cybertim** [comment]
As mentioned in the Store listing, Help and Settings of the App, https://cryptocompare.com  is used as the source of conversion/history data.
And cryptocompare uses a 'average of all exchanges' value called 'CryptoCompare Current Aggregate'.
You can read more about this here:
https://www.cryptocompare.com/coins/guides/how-does-our-cryptocurrecy-index-work/

**Comment by svenjatzu** [comment]
Thanks for your answer. 
It seems like I have a shapeshiftercoin.
I can’t find it anywhere but I can add it ass token inside the wallet.
It shows me an value that I don’t find anywhere else.
On cryptocompare the coins shortcode is used for other coins and my coin isn’t even listet oncryptocompare.
I just really don’t understand anything anymore.
Can you please help me clearing this prob?

**Comment by cybertim** [comment]
Can you give any info in this 'shapeshiftercoin'. Google doesn't give me any results..

**Comment by svenjatzu** [comment]
The coin is called premine pre, on cryptocompare I just can find with the tag pre premium and presearch. For token contract I used this Adresse https://etherscan.io/token/0x30765406d51091ed78ff13c107731daf3be5ef16 and also my coins are inside. 
Is there maybe a name miswriting and premine is premium?

**Comment by cybertim** [comment]
The App makes an API call to cryptocompare with the Symbol as the parameter. In this case the 'Premine' Token Contract uses the symbol 'PRE' which is also being used by 'Premium' https://www.cryptocompare.com/coins/pre/overview

So you are probably getting the value of 'Premium' for this 'Premine' token.
I can't seem to find any value for 'Premine' so yeah, you could probably rename the Token to 'PRE_' or something in the App to prevent the value from being shown.
