### ISSUE TITLE
panther64

### ISSUE THREAD

**Issue by panther64** [cybertim/blockwallet#43]
Hello i transferred some ox out of a coinspot wallet saturday night around 9pm australian time.i sent them to my block wallet where i keep my ethereum. They were sent to the ZRX OXPROTOCOL contract address. They still have not turned up i was wondering if they should have been sent the my ethereum address instaed of the ZRX contract address. Coinspot sent me a confirmation re the successful transfer toady after emailling them . I can find the contract address on the etherscan ethereum block explorer but do not have a clue how to get them into my block wallet. Any assistance would help. Please bear in mind i am new to this token and crypto stuff and its rather complex. I hope i havnt done the wrong thing and lost my tokens.  I am happy to supply the contract address if need but some advise would be very helpful.

**Comment by cybertim** [comment]
For starters, you can check your public ethereum address of 'coinspot wallet' on https://etherscan.io. Etherscan does also index the contract token transfers on address basis, so you should see the transaction listed there. The transaction itself can give you an answer to whether you used the correct address or not (where the tokens went) or if the transaction was even successful at all.  Hope it helps.

**Comment by panther64** [comment]
Thankyou so much for your input. Much appreciated.

------ Original Message ------
