### ISSUE TITLE
Coin transfer not showing on block wallet

### ISSUE THREAD

**Issue by akibechoudhury** [cybertim/blockwallet#45]
Some coins were sent to my address from under the "Receive" tab and I can see the confirmation from etherscan.io, but they don't show up in my block wallet. I think that it might be because the coin I'm trying to receive isn't listed on the app (INS), can someone please confirm this and also let me know how I can recover my coins?

Thanks

**Comment by cybertim** [comment]
You need to add the ERC20 Token to your overview before you can see it in Blockwallet.
I've added [INS](https://etherscan.io/token/0x5b2e4a700dfbc560061e957edec8f6eeeb74a320#readContract) to the Pop. token list (see for details #38 ) so when its available in the App just add it to the list and you will see the value.

**Comment by cybertim** [comment]
closed due inactivity
