### ISSUE TITLE
Wallet Refuses to Open

### ISSUE THREAD

**Issue by FrankyJB** [cybertim/blockwallet#50]
Tim I have used BW successfullly for months on Ios but today when you open BW it brings up coinlist but will not open, just spinning like a constant refresh. My freind rang me having this issue and when I tried to open mine it was the same issue. Is this happening with anyone else, do you have a solution?
Cannot get a balance on funds or transact.
FB

**Comment by cybertim** [comment]
Yes currently I have a payment issue with my hosting provider (creditcard issues of some sort).
They are solving the matter but in the process they sadly blocked the server..  
I did open multiple tickets hoping they will resolve the issue asap... already got some replies but still no solution sadly.

Also, it's pretty shocking they blocked access to the server while sorting the matter as well.. I do rent server from the company on a professional level as well, so this opened my eyes to reconsider their services tho..

**Comment by FrankyJB** [comment]
So Tim if you dont pay your server bill i lose access to the server so i lose access to my funds correct, 
That is not a very good way to run an international business you are dealing in other peoples money basically, no point blaming the server company it would be in their terms i suggest you have a read of them and when can we expext to have access again.

**Comment by cybertim** [comment]
This is not entirely correct and even very rude and inappropriate to make such acquisitions.

For one, you did not lose access to your fund. The wallet operates perfectly without my FREE service i am paying for from my own pocket.
You can just host your own Geth and change the server address in the settings of the app or just export your keys whenever you like.

**Comment by FrankyJB** [comment]
Hi Tim
I apologise for my rudeness.
FB

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
