### ISSUE TITLE
transferring xyo tokens

### ISSUE THREAD

**Issue by happ68** [cybertim/blockwallet#55]
Hi Tim and sorry to bother you mate. I am trying to transfer out of my Block wallet some XYO tokens i have in there. I originally transferred them from my trust wallet to the block wallet and i am now trying to transfer them back to my trust wallet. The issue i am having is everytime i go into the block wallet and send them it charges me gas from my ethereum balance and says that the tokens are sent but they dont leave the block wallet. I have been charged small amounts of ethereum everytime i try and send them but they never leave the wallet even after thousands of confirmations. Would you have any idea as to why this happens.The last attempt i made was on the 2nd of oct at 4.30.They were sent from 0xd140cb6da1f9f3c5ba5be7e456fcdc98c58fb8ff. Any assistance would be appreciated. regards Peter

**Comment by cybertim** [comment]
Etherscan has a nice system which detects reasons why transaction fail:
https://etherscan.io/tx/0x42819252cd4253af8430821a454dea21fb9df4d3d781c4b7cce860afe86d9a96
Click on the failed reason ("Unable To Locate Corresponding Transfer Event Logs") takes you to this page:
https://etherscancom.freshdesk.com/support/solutions/articles/35000048534-the-erc-20-token-transfer-might-have-failed
If you look at other transactions within the contract:
https://etherscan.io/address/0x55296f69f40ea6d20e478533c15a6b08b654e758#
You'll notice they need around 30k gas, so 53k should be enough I guess.
If you check the balance on the contract you'll get: 220000000000000000000000 (before 18 decimals)
and you are trying to send: 20000000000000000000000 (before 18 decimals)
So balance shouldn't be an issue. I'm not 100% sure why the transactions is not coming through, maybe it has to do with the contract (Frozen?). 
On 'the internet' you read people solving the "Unable To Locate Corresponding Transfer Event Logs" issue by setting the Gas Limit on 100k and lowering the gas price to around 4GWei, implicating it's a gas limit issue. But before burning your ETH like this, I would try to get some intel from the contract-creators. Or maybe a forum dedicated to the Token.
