### ISSUE TITLE
How do o get my coins off my iPhone app?

### ISSUE THREAD

**Issue by miersha** [cybertim/blockwallet#56]
I was wondering how I get my
Crypto off of my iPhone app since it is no longer available?

**Comment by cybertim** [comment]
Sadly, there were not enough donations to extend the Apple Developer Program for the iOS App Store. 
Info about installed apps that are not available anymore in the store: https://developer.apple.com/support/renewal

To be safe, make a backup from within blockwallet, this way you can always recover through blockwallet.eu/keytools/ and easily migrate to another wallet.
