### ISSUE TITLE
Blockwallet cant access funds BTC

### ISSUE THREAD

**Issue by MrCoCo2021** [cybertim/blockwallet#59]
Hi how are you? 
I hope your well ! 
 I am so thankful that I have found you 
I've been going crazy the past few weeks trying to figure out what to do.
Ok so heres my situation I downloaded blockwallet from the app store in 2017 on my iPhone I've since then changed phone 3 times a few weeks back when all the bitcoin craze was happening I tried to open my app its opens but I have 0 funds although my history shown that I received 0.2 BTC back in 2017 but I never touched it's gone... what can I do ? I'm so desperate for help please 
If you could kindly help me 
🙏🏼

**Comment by MrCoCo2021** [comment]
![Screenshot_20210128-184424_Chrome](https://user-images.githubusercontent.com/78235418/106352718-c61df780-62fe-11eb-87f8-ec1e1645f2f9.jpg)

**Comment by cybertim** [comment]
Sorry, 
This is the ethereum only blockwallet(.eu) the App you are referring to is found here: https://github.com/Blockwallet
