### ISSUE TITLE
Implement ERC20 Tokens balance and transfer

### ISSUE THREAD

**Issue by cybertim** [cybertim/blockwallet#9]
https://github.com/ethereum/EIPs/issues/20

**Comment by cybertim** [comment]
Balance has been implemented, transfer is almost done. Will come in the next release.

**Comment by brianerdelyi** [comment]
I can receive ERC20 tokens.  looking forward to sending ERC20 tokens :)

**Comment by cybertim** [comment]
transfer now implemented in 1.1.0 (android: live, ios: now in review)
